/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Name = 1;
  /** RegularExpression Id. */
  int NameChar = 2;
  /** RegularExpression Id. */
  int NameStarChar = 3;
  /** RegularExpression Id. */
  int S = 4;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Flotante = 6;
  /** RegularExpression Id. */
  int ETIXML = 7;
  /** RegularExpression Id. */
  int ETIFUNCION = 8;
  /** RegularExpression Id. */
  int ETIFUNCIONRETURN = 9;
  /** RegularExpression Id. */
  int ETIBLOQUE = 10;
  /** RegularExpression Id. */
  int ETINEXT2 = 11;
  /** RegularExpression Id. */
  int ETIFINNEXT2 = 12;
  /** RegularExpression Id. */
  int ETIFINSTATEMENT2 = 13;
  /** RegularExpression Id. */
  int FINSTAT3 = 14;
  /** RegularExpression Id. */
  int ETIFINXML2 = 15;
  /** RegularExpression Id. */
  int ETIFXML2 = 16;
  /** RegularExpression Id. */
  int ETIFINXML = 17;
  /** RegularExpression Id. */
  int ETIFINBLOQUE = 18;
  /** RegularExpression Id. */
  int ETIPRINT = 19;
  /** RegularExpression Id. */
  int ETIVARSET = 20;
  /** RegularExpression Id. */
  int ETIPROMPT = 21;
  /** RegularExpression Id. */
  int ETINEXT = 22;
  /** RegularExpression Id. */
  int ETIVARGET = 23;
  /** RegularExpression Id. */
  int ETIFINSTATEMENT = 24;
  /** RegularExpression Id. */
  int ETILLAMAFUNCION = 25;
  /** RegularExpression Id. */
  int ETIARGUMENTOS = 26;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC = 27;
  /** RegularExpression Id. */
  int ETIMATHNUMBER = 28;
  /** RegularExpression Id. */
  int ETIVALUENAMEB = 29;
  /** RegularExpression Id. */
  int ETIIF = 30;
  /** RegularExpression Id. */
  int ETILOGIC = 31;
  /** RegularExpression Id. */
  int ETIDO0 = 32;
  /** RegularExpression Id. */
  int ETIADD3 = 33;
  /** RegularExpression Id. */
  int ETILLFUNCIONRETURN = 34;
  /** RegularExpression Id. */
  int FINBLO = 35;
  /** RegularExpression Id. */
  int TEXTOPRINT = 36;
  /** RegularExpression Id. */
  int TEXT2 = 37;
  /** RegularExpression Id. */
  int CARACTER = 38;
  /** RegularExpression Id. */
  int ETITEXT = 39;
  /** RegularExpression Id. */
  int ETIPRINTNUM = 40;
  /** RegularExpression Id. */
  int ETIBLOCKGET = 41;
  /** RegularExpression Id. */
  int ETIFINVALU = 42;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC2 = 43;
  /** RegularExpression Id. */
  int ETITEXTJOIN = 44;
  /** RegularExpression Id. */
  int ETIADD2 = 45;
  /** RegularExpression Id. */
  int ETILLFUNCIONRETURN2 = 46;
  /** RegularExpression Id. */
  int CARACTER2 = 47;
  /** RegularExpression Id. */
  int CARACTER3 = 48;
  /** RegularExpression Id. */
  int ETINAMEVALUE = 49;
  /** RegularExpression Id. */
  int ETIFINVALU2 = 50;
  /** RegularExpression Id. */
  int CARACTER8 = 51;
  /** RegularExpression Id. */
  int CARACTER9 = 52;
  /** RegularExpression Id. */
  int MATHNUMBER = 53;
  /** RegularExpression Id. */
  int FINVALUE = 54;
  /** RegularExpression Id. */
  int VARGET = 55;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC3 = 56;
  /** RegularExpression Id. */
  int ETIMUTATION = 57;
  /** RegularExpression Id. */
  int ETIMUTATIONTEXT = 58;
  /** RegularExpression Id. */
  int CARACTER6 = 59;
  /** RegularExpression Id. */
  int CARACTER7 = 60;
  /** RegularExpression Id. */
  int ETINUMBERPROMPT = 61;
  /** RegularExpression Id. */
  int ETIFINVALUEPROMPT = 62;
  /** RegularExpression Id. */
  int CARACTER10 = 63;
  /** RegularExpression Id. */
  int NOMFUN = 64;
  /** RegularExpression Id. */
  int ARGUMENTOS = 65;
  /** RegularExpression Id. */
  int NOMBRE = 66;
  /** RegularExpression Id. */
  int ARGUM = 67;
  /** RegularExpression Id. */
  int DESCRIPCI = 68;
  /** RegularExpression Id. */
  int DESCRIPC = 69;
  /** RegularExpression Id. */
  int DESCRIPCION = 70;
  /** RegularExpression Id. */
  int STATEM = 71;
  /** RegularExpression Id. */
  int NOMBREFUN = 72;
  /** RegularExpression Id. */
  int FUNC = 73;
  /** RegularExpression Id. */
  int FINLLAMAFUNCION = 74;
  /** RegularExpression Id. */
  int ARGUMENTO = 75;
  /** RegularExpression Id. */
  int LLFVAR = 76;
  /** RegularExpression Id. */
  int LLFTEXT = 77;
  /** RegularExpression Id. */
  int LLFARG = 78;
  /** RegularExpression Id. */
  int ETIFINLLAMAFUNCION = 79;
  /** RegularExpression Id. */
  int OPADD = 80;
  /** RegularExpression Id. */
  int OPMINUS = 81;
  /** RegularExpression Id. */
  int OPMULTIPLY = 82;
  /** RegularExpression Id. */
  int OPDIVIDE = 83;
  /** RegularExpression Id. */
  int OPEQ = 84;
  /** RegularExpression Id. */
  int OPNEQ = 85;
  /** RegularExpression Id. */
  int OPLT = 86;
  /** RegularExpression Id. */
  int OPLTE = 87;
  /** RegularExpression Id. */
  int OPGT = 88;
  /** RegularExpression Id. */
  int OPGTE = 89;
  /** RegularExpression Id. */
  int CAR = 90;
  /** RegularExpression Id. */
  int VRETURN = 91;
  /** RegularExpression Id. */
  int FINSTA = 92;
  /** RegularExpression Id. */
  int ETIELSE = 93;
  /** RegularExpression Id. */
  int FINSTAT2 = 94;
  /** RegularExpression Id. */
  int ETINEXT3 = 95;
  /** RegularExpression Id. */
  int ETIADD = 96;
  /** RegularExpression Id. */
  int ETIFUN2 = 97;
  /** RegularExpression Id. */
  int ETIFUNRET2 = 98;
  /** RegularExpression Id. */
  int ETIBLO2 = 99;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int XML = 1;
  /** Lexical state. */
  int ETIFXML = 2;
  /** Lexical state. */
  int BLOQUE = 3;
  /** Lexical state. */
  int FINBLOQUE = 4;
  /** Lexical state. */
  int PRINT = 5;
  /** Lexical state. */
  int TEXT1 = 6;
  /** Lexical state. */
  int TEXT = 7;
  /** Lexical state. */
  int SIGUIENTE = 8;
  /** Lexical state. */
  int NOM = 9;
  /** Lexical state. */
  int NOMVAR = 10;
  /** Lexical state. */
  int FINNOMVAR = 11;
  /** Lexical state. */
  int NUM = 12;
  /** Lexical state. */
  int NUM2 = 13;
  /** Lexical state. */
  int SIG = 14;
  /** Lexical state. */
  int TEXTPROMPT = 15;
  /** Lexical state. */
  int FRASEPROMPT = 16;
  /** Lexical state. */
  int FRASEPROMPT2 = 17;
  /** Lexical state. */
  int FRASEPROMPT3 = 18;
  /** Lexical state. */
  int TEXTOPROMPT = 19;
  /** Lexical state. */
  int FUNCION = 20;
  /** Lexical state. */
  int NOMFUNCION = 21;
  /** Lexical state. */
  int ARGUN = 22;
  /** Lexical state. */
  int DESCRIPCIONFUNCION = 23;
  /** Lexical state. */
  int DES = 24;
  /** Lexical state. */
  int DESCRIP = 25;
  /** Lexical state. */
  int STATEMENT = 26;
  /** Lexical state. */
  int LLAMAFUNCION = 27;
  /** Lexical state. */
  int LLAMAFUN = 28;
  /** Lexical state. */
  int ARGUMENTOSFUN = 29;
  /** Lexical state. */
  int ARGU = 30;
  /** Lexical state. */
  int NOMVARLLF = 31;
  /** Lexical state. */
  int FINLLF = 32;
  /** Lexical state. */
  int OP = 33;
  /** Lexical state. */
  int OPLOGIC = 34;
  /** Lexical state. */
  int VARRETURN = 35;
  /** Lexical state. */
  int VARRETURN2 = 36;
  /** Lexical state. */
  int FINSTATEMENT = 37;
  /** Lexical state. */
  int TEXTJOIN = 38;
  /** Lexical state. */
  int ETIFUNCION2 = 39;
  /** Lexical state. */
  int ETIFUNCIONRETURN2 = 40;
  /** Lexical state. */
  int ETIBLOQUE2 = 41;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Name>",
    "<NameChar>",
    "<NameStarChar>",
    "<S>",
    "<Entero>",
    "<Flotante>",
    "\"<xml\"",
    "<ETIFUNCION>",
    "<ETIFUNCIONRETURN>",
    "<ETIBLOQUE>",
    "<ETINEXT2>",
    "<ETIFINNEXT2>",
    "<ETIFINSTATEMENT2>",
    "<FINSTAT3>",
    "<ETIFINXML2>",
    "\">\"",
    "\"/xml\"",
    "<ETIFINBLOQUE>",
    "<ETIPRINT>",
    "<ETIVARSET>",
    "<ETIPROMPT>",
    "<ETINEXT>",
    "<ETIVARGET>",
    "<ETIFINSTATEMENT>",
    "<ETILLAMAFUNCION>",
    "<ETIARGUMENTOS>",
    "<ETIMATHARITHMETIC>",
    "<ETIMATHNUMBER>",
    "<ETIVALUENAMEB>",
    "<ETIIF>",
    "<ETILOGIC>",
    "<ETIDO0>",
    "<ETIADD3>",
    "<ETILLFUNCIONRETURN>",
    "<FINBLO>",
    "<TEXTOPRINT>",
    "<TEXT2>",
    "<CARACTER>",
    "<ETITEXT>",
    "<ETIPRINTNUM>",
    "<ETIBLOCKGET>",
    "<ETIFINVALU>",
    "<ETIMATHARITHMETIC2>",
    "<ETITEXTJOIN>",
    "<ETIADD2>",
    "<ETILLFUNCIONRETURN2>",
    "<CARACTER2>",
    "<CARACTER3>",
    "<ETINAMEVALUE>",
    "<ETIFINVALU2>",
    "<CARACTER8>",
    "<CARACTER9>",
    "<MATHNUMBER>",
    "<FINVALUE>",
    "<VARGET>",
    "<ETIMATHARITHMETIC3>",
    "<ETIMUTATION>",
    "<ETIMUTATIONTEXT>",
    "<CARACTER6>",
    "<CARACTER7>",
    "<ETINUMBERPROMPT>",
    "<ETIFINVALUEPROMPT>",
    "<CARACTER10>",
    "<NOMFUN>",
    "<ARGUMENTOS>",
    "<NOMBRE>",
    "<ARGUM>",
    "<DESCRIPCI>",
    "<DESCRIPC>",
    "<DESCRIPCION>",
    "<STATEM>",
    "<NOMBREFUN>",
    "<FUNC>",
    "<FINLLAMAFUNCION>",
    "<ARGUMENTO>",
    "<LLFVAR>",
    "<LLFTEXT>",
    "<LLFARG>",
    "<ETIFINLLAMAFUNCION>",
    "\"field name=\\\"OP\\\">ADD\"",
    "\"field name=\\\"OP\\\">MINUS\"",
    "\"field name=\\\"OP\\\">MULTIPLY\"",
    "\"field name=\\\"OP\\\">DIVIDE\"",
    "\"field name=\\\"OP\\\">EQ\"",
    "\"field name=\\\"OP\\\">NEQ\"",
    "\"field name=\\\"OP\\\">LT\"",
    "\"field name=\\\"OP\\\">LTE\"",
    "\"field name=\\\"OP\\\">GT\"",
    "\"field name=\\\"OP\\\">GTE\"",
    "<CAR>",
    "<VRETURN>",
    "\"</block\"",
    "\"statement name=\\\"ELSE\\\"\"",
    "<FINSTAT2>",
    "\"<next\"",
    "<ETIADD>",
    "<ETIFUN2>",
    "<ETIFUNRET2>",
    "<ETIBLO2>",
    "<token of kind 100>",
  };

}
