/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Name = 1;
  /** RegularExpression Id. */
  int NameChar = 2;
  /** RegularExpression Id. */
  int NameStarChar = 3;
  /** RegularExpression Id. */
  int S = 4;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Flotante = 6;
  /** RegularExpression Id. */
  int ETIXML = 7;
  /** RegularExpression Id. */
  int ETIBLOQUE = 8;
  /** RegularExpression Id. */
  int ETIPRINT = 11;
  /** RegularExpression Id. */
  int ETIFIN = 12;
  /** RegularExpression Id. */
  int ETITEXT = 13;
  /** RegularExpression Id. */
  int TEXTOPRINT = 14;
  /** RegularExpression Id. */
  int CARACTER = 15;
  /** RegularExpression Id. */
  int CARACTER2 = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int XML = 1;
  /** Lexical state. */
  int BLOQUE = 2;
  /** Lexical state. */
  int PRINT = 3;
  /** Lexical state. */
  int TEXT = 4;
  /** Lexical state. */
  int TEXT1 = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Name>",
    "<NameChar>",
    "<NameStarChar>",
    "<S>",
    "<Entero>",
    "<Flotante>",
    "\"<xml\"",
    "\"<block\"",
    "\"/block>\"",
    "\"/xml>\"",
    "<ETIPRINT>",
    "<ETIFIN>",
    "<ETITEXT>",
    "<TEXTOPRINT>",
    "<CARACTER>",
    "<CARACTER2>",
    "<token of kind 17>",
  };

}
