/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Name = 1;
  /** RegularExpression Id. */
  int NameChar = 2;
  /** RegularExpression Id. */
  int NameStarChar = 3;
  /** RegularExpression Id. */
  int S = 4;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Flotante = 6;
  /** RegularExpression Id. */
  int ETIXML = 7;
  /** RegularExpression Id. */
  int ETIFUNCION = 8;
  /** RegularExpression Id. */
  int ETIBLOQUE = 9;
  /** RegularExpression Id. */
  int ETIFINXML = 10;
  /** RegularExpression Id. */
  int ETIFINBLOQUE = 11;
  /** RegularExpression Id. */
  int ETIPRINT = 12;
  /** RegularExpression Id. */
  int ETIVARSET = 13;
  /** RegularExpression Id. */
  int ETIPROMPT = 14;
  /** RegularExpression Id. */
  int ETINEXT = 15;
  /** RegularExpression Id. */
  int ETIVARGET = 16;
  /** RegularExpression Id. */
  int ETIFINSTATEMENT = 17;
  /** RegularExpression Id. */
  int ETILLAMAFUNCION = 18;
  /** RegularExpression Id. */
  int ETIARGUMENTOS = 19;
  /** RegularExpression Id. */
  int ETIFINLLAMAFUNCION = 20;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC = 21;
  /** RegularExpression Id. */
  int ETIMATHNUMBER = 22;
  /** RegularExpression Id. */
  int ETIVALUENAMEB = 23;
  /** RegularExpression Id. */
  int TEXTOPRINT = 24;
  /** RegularExpression Id. */
  int TEXT2 = 25;
  /** RegularExpression Id. */
  int CARACTER = 26;
  /** RegularExpression Id. */
  int ETITEXT = 27;
  /** RegularExpression Id. */
  int ETIPRINTNUM = 28;
  /** RegularExpression Id. */
  int ETIBLOCKGET = 29;
  /** RegularExpression Id. */
  int ETIFINVALUE = 30;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC2 = 31;
  /** RegularExpression Id. */
  int CARACTER2 = 32;
  /** RegularExpression Id. */
  int CARACTER3 = 33;
  /** RegularExpression Id. */
  int CARACTER4 = 34;
  /** RegularExpression Id. */
  int CARACTER5 = 35;
  /** RegularExpression Id. */
  int CARACTER8 = 36;
  /** RegularExpression Id. */
  int CARACTER9 = 37;
  /** RegularExpression Id. */
  int FINVALUE = 38;
  /** RegularExpression Id. */
  int VARGET = 39;
  /** RegularExpression Id. */
  int ETIMUTATION = 40;
  /** RegularExpression Id. */
  int ETIMUTATIONTEXT = 41;
  /** RegularExpression Id. */
  int CARACTER6 = 42;
  /** RegularExpression Id. */
  int CARACTER7 = 43;
  /** RegularExpression Id. */
  int ETINUMBERPROMPT = 44;
  /** RegularExpression Id. */
  int ETIFINVALUEPROMPT = 45;
  /** RegularExpression Id. */
  int CARACTER10 = 46;
  /** RegularExpression Id. */
  int CARACTER11 = 47;
  /** RegularExpression Id. */
  int NOMFUN = 48;
  /** RegularExpression Id. */
  int ARGUMENTOS = 49;
  /** RegularExpression Id. */
  int NOMBRE = 50;
  /** RegularExpression Id. */
  int ARGUM = 51;
  /** RegularExpression Id. */
  int DESCRIPCI = 52;
  /** RegularExpression Id. */
  int DESCRIPC = 53;
  /** RegularExpression Id. */
  int DESCRIPCION = 54;
  /** RegularExpression Id. */
  int STATEM = 55;
  /** RegularExpression Id. */
  int NOMBREFUN = 56;
  /** RegularExpression Id. */
  int FUNC = 57;
  /** RegularExpression Id. */
  int FINLLAMAFUNCION = 58;
  /** RegularExpression Id. */
  int ARGUMENTO = 59;
  /** RegularExpression Id. */
  int LLFVAR = 60;
  /** RegularExpression Id. */
  int LLFTEXT = 61;
  /** RegularExpression Id. */
  int LLFARG = 62;
  /** RegularExpression Id. */
  int FINLLFUNCION = 63;
  /** RegularExpression Id. */
  int OPADD = 64;
  /** RegularExpression Id. */
  int OPMINUS = 65;
  /** RegularExpression Id. */
  int OPMULTIPLY = 66;
  /** RegularExpression Id. */
  int OPDIVIDE = 67;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int XML = 1;
  /** Lexical state. */
  int BLOQUE = 2;
  /** Lexical state. */
  int PRINT = 3;
  /** Lexical state. */
  int TEXT1 = 4;
  /** Lexical state. */
  int TEXT = 5;
  /** Lexical state. */
  int SIGUIENTE = 6;
  /** Lexical state. */
  int NOM = 7;
  /** Lexical state. */
  int NOMVAR = 8;
  /** Lexical state. */
  int NOM2 = 9;
  /** Lexical state. */
  int NOMVAR2 = 10;
  /** Lexical state. */
  int NUM = 11;
  /** Lexical state. */
  int NUM2 = 12;
  /** Lexical state. */
  int SIG = 13;
  /** Lexical state. */
  int TEXTPROMPT = 14;
  /** Lexical state. */
  int FRASEPROMPT = 15;
  /** Lexical state. */
  int FRASEPROMPT2 = 16;
  /** Lexical state. */
  int FRASEPROMPT3 = 17;
  /** Lexical state. */
  int TEXTOPROMPT = 18;
  /** Lexical state. */
  int TEXTOPROMPT2 = 19;
  /** Lexical state. */
  int FUNCION = 20;
  /** Lexical state. */
  int NOMFUNCION = 21;
  /** Lexical state. */
  int ARGUN = 22;
  /** Lexical state. */
  int DESCRIPCIONFUNCION = 23;
  /** Lexical state. */
  int DES = 24;
  /** Lexical state. */
  int DESCRIP = 25;
  /** Lexical state. */
  int STATEMENT = 26;
  /** Lexical state. */
  int LLAMAFUNCION = 27;
  /** Lexical state. */
  int LLAMAFUN = 28;
  /** Lexical state. */
  int ARGUMENTOSFUN = 29;
  /** Lexical state. */
  int ARGU = 30;
  /** Lexical state. */
  int NOMVARLLF = 31;
  /** Lexical state. */
  int FINLLF = 32;
  /** Lexical state. */
  int OP = 33;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Name>",
    "<NameChar>",
    "<NameStarChar>",
    "<S>",
    "<Entero>",
    "<Flotante>",
    "\"<xml\"",
    "\"<block type=\\\"procedures_defnoreturn\"",
    "\"<block\"",
    "\"/xml>\"",
    "\"/block>\"",
    "<ETIPRINT>",
    "<ETIVARSET>",
    "<ETIPROMPT>",
    "<ETINEXT>",
    "<ETIVARGET>",
    "<ETIFINSTATEMENT>",
    "<ETILLAMAFUNCION>",
    "<ETIARGUMENTOS>",
    "<ETIFINLLAMAFUNCION>",
    "<ETIMATHARITHMETIC>",
    "<ETIMATHNUMBER>",
    "<ETIVALUENAMEB>",
    "<TEXTOPRINT>",
    "<TEXT2>",
    "<CARACTER>",
    "<ETITEXT>",
    "<ETIPRINTNUM>",
    "<ETIBLOCKGET>",
    "<ETIFINVALUE>",
    "<ETIMATHARITHMETIC2>",
    "<CARACTER2>",
    "<CARACTER3>",
    "<CARACTER4>",
    "<CARACTER5>",
    "<CARACTER8>",
    "<CARACTER9>",
    "<FINVALUE>",
    "<VARGET>",
    "<ETIMUTATION>",
    "<ETIMUTATIONTEXT>",
    "<CARACTER6>",
    "<CARACTER7>",
    "<ETINUMBERPROMPT>",
    "<ETIFINVALUEPROMPT>",
    "<CARACTER10>",
    "<CARACTER11>",
    "<NOMFUN>",
    "<ARGUMENTOS>",
    "<NOMBRE>",
    "<ARGUM>",
    "<DESCRIPCI>",
    "<DESCRIPC>",
    "<DESCRIPCION>",
    "<STATEM>",
    "<NOMBREFUN>",
    "<FUNC>",
    "<FINLLAMAFUNCION>",
    "<ARGUMENTO>",
    "<LLFVAR>",
    "<LLFTEXT>",
    "<LLFARG>",
    "\"</v\"",
    "\"field name=\\\"OP\\\">ADD\"",
    "\"field name=\\\"OP\\\">MINUS\"",
    "\"field name=\\\"OP\\\">MULTIPLY\"",
    "\"field name=\\\"OP\\\">DIVIDE\"",
    "<token of kind 68>",
  };

}
