/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Name = 1;
  /** RegularExpression Id. */
  int NameChar = 2;
  /** RegularExpression Id. */
  int NameStarChar = 3;
  /** RegularExpression Id. */
  int S = 4;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Flotante = 6;
  /** RegularExpression Id. */
  int ETIXML = 7;
  /** RegularExpression Id. */
  int ETIBLOQUE = 8;
  /** RegularExpression Id. */
  int ETIFINXML = 9;
  /** RegularExpression Id. */
  int ETIFINBLOQUE = 10;
  /** RegularExpression Id. */
  int ETIPRINT = 11;
  /** RegularExpression Id. */
  int ETIFIN = 12;
  /** RegularExpression Id. */
  int ETIVARSET = 13;
  /** RegularExpression Id. */
  int ETIPROMPT = 14;
  /** RegularExpression Id. */
  int ETINEXT = 15;
  /** RegularExpression Id. */
  int ETIVARGET = 16;
  /** RegularExpression Id. */
  int ETIFINNEXT = 17;
  /** RegularExpression Id. */
  int TEXTOPRINT = 18;
  /** RegularExpression Id. */
  int TEXT2 = 19;
  /** RegularExpression Id. */
  int CARACTER = 20;
  /** RegularExpression Id. */
  int ETITEXT = 21;
  /** RegularExpression Id. */
  int ETIBLOCKGET = 22;
  /** RegularExpression Id. */
  int ETIFINVALUE = 23;
  /** RegularExpression Id. */
  int CARACTER2 = 24;
  /** RegularExpression Id. */
  int CARACTER3 = 25;
  /** RegularExpression Id. */
  int CARACTER4 = 26;
  /** RegularExpression Id. */
  int CARACTER5 = 27;
  /** RegularExpression Id. */
  int CARACTER8 = 28;
  /** RegularExpression Id. */
  int CARACTER9 = 29;
  /** RegularExpression Id. */
  int ETIMUTATION = 30;
  /** RegularExpression Id. */
  int ETIMUTATIONTEXT = 31;
  /** RegularExpression Id. */
  int CARACTER6 = 32;
  /** RegularExpression Id. */
  int CARACTER7 = 33;
  /** RegularExpression Id. */
  int ETINUMBERPROMPT = 34;
  /** RegularExpression Id. */
  int ETIFINVALUEPROMPT = 35;
  /** RegularExpression Id. */
  int CARACTER10 = 36;
  /** RegularExpression Id. */
  int CARACTER11 = 37;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int XML = 1;
  /** Lexical state. */
  int BLOQUE = 2;
  /** Lexical state. */
  int PRINT = 3;
  /** Lexical state. */
  int TEXT1 = 4;
  /** Lexical state. */
  int TEXT = 5;
  /** Lexical state. */
  int SIGUIENTE = 6;
  /** Lexical state. */
  int NOM = 7;
  /** Lexical state. */
  int NOMVAR = 8;
  /** Lexical state. */
  int NOM2 = 9;
  /** Lexical state. */
  int NOMVAR2 = 10;
  /** Lexical state. */
  int NUM = 11;
  /** Lexical state. */
  int NUM2 = 12;
  /** Lexical state. */
  int TEXTPROMPT = 13;
  /** Lexical state. */
  int FRASEPROMPT = 14;
  /** Lexical state. */
  int FRASEPROMPT2 = 15;
  /** Lexical state. */
  int FRASEPROMPT3 = 16;
  /** Lexical state. */
  int TEXTOPROMPT = 17;
  /** Lexical state. */
  int TEXTOPROMPT2 = 18;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Name>",
    "<NameChar>",
    "<NameStarChar>",
    "<S>",
    "<Entero>",
    "<Flotante>",
    "\"<xml\"",
    "\"<block\"",
    "\"/xml>\"",
    "\"/block>\"",
    "<ETIPRINT>",
    "<ETIFIN>",
    "<ETIVARSET>",
    "<ETIPROMPT>",
    "<ETINEXT>",
    "<ETIVARGET>",
    "<ETIFINNEXT>",
    "<TEXTOPRINT>",
    "<TEXT2>",
    "<CARACTER>",
    "<ETITEXT>",
    "<ETIBLOCKGET>",
    "<ETIFINVALUE>",
    "<CARACTER2>",
    "<CARACTER3>",
    "<CARACTER4>",
    "<CARACTER5>",
    "<CARACTER8>",
    "<CARACTER9>",
    "<ETIMUTATION>",
    "<ETIMUTATIONTEXT>",
    "<CARACTER6>",
    "<CARACTER7>",
    "<ETINUMBERPROMPT>",
    "<ETIFINVALUEPROMPT>",
    "<CARACTER10>",
    "<CARACTER11>",
    "<token of kind 38>",
  };

}
