/* Generated By:JavaCC: Do not edit this line. practicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Name = 1;
  /** RegularExpression Id. */
  int NameChar = 2;
  /** RegularExpression Id. */
  int NameStarChar = 3;
  /** RegularExpression Id. */
  int S = 4;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Flotante = 6;
  /** RegularExpression Id. */
  int ETIXML = 7;
  /** RegularExpression Id. */
  int ETIFUNCION = 8;
  /** RegularExpression Id. */
  int ETIBLOQUE = 9;
  /** RegularExpression Id. */
  int ETINEXT2 = 10;
  /** RegularExpression Id. */
  int ETIFINNEXT2 = 11;
  /** RegularExpression Id. */
  int ETIFINXML = 12;
  /** RegularExpression Id. */
  int ETIFINBLOQUE = 13;
  /** RegularExpression Id. */
  int ETIPRINT = 14;
  /** RegularExpression Id. */
  int ETIVARSET = 15;
  /** RegularExpression Id. */
  int ETIPROMPT = 16;
  /** RegularExpression Id. */
  int ETINEXT = 17;
  /** RegularExpression Id. */
  int ETIVARGET = 18;
  /** RegularExpression Id. */
  int ETIFINSTATEMENT = 19;
  /** RegularExpression Id. */
  int ETILLAMAFUNCION = 20;
  /** RegularExpression Id. */
  int ETIARGUMENTOS = 21;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC = 22;
  /** RegularExpression Id. */
  int ETIMATHNUMBER = 23;
  /** RegularExpression Id. */
  int ETIVALUENAMEB = 24;
  /** RegularExpression Id. */
  int ETIIF = 25;
  /** RegularExpression Id. */
  int ETILOGIC = 26;
  /** RegularExpression Id. */
  int ETIDO0 = 27;
  /** RegularExpression Id. */
  int FINBLO = 28;
  /** RegularExpression Id. */
  int TEXTOPRINT = 29;
  /** RegularExpression Id. */
  int TEXT2 = 30;
  /** RegularExpression Id. */
  int CARACTER = 31;
  /** RegularExpression Id. */
  int ETITEXT = 32;
  /** RegularExpression Id. */
  int ETIPRINTNUM = 33;
  /** RegularExpression Id. */
  int ETIBLOCKGET = 34;
  /** RegularExpression Id. */
  int ETIFINVALU = 35;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC2 = 36;
  /** RegularExpression Id. */
  int CARACTER2 = 37;
  /** RegularExpression Id. */
  int CARACTER3 = 38;
  /** RegularExpression Id. */
  int ETINAMEVALUE = 39;
  /** RegularExpression Id. */
  int ETIFINVALU2 = 40;
  /** RegularExpression Id. */
  int CARACTER8 = 41;
  /** RegularExpression Id. */
  int CARACTER9 = 42;
  /** RegularExpression Id. */
  int MATHNUMBER = 43;
  /** RegularExpression Id. */
  int FINVALUE = 44;
  /** RegularExpression Id. */
  int VARGET = 45;
  /** RegularExpression Id. */
  int ETIMATHARITHMETIC3 = 46;
  /** RegularExpression Id. */
  int ETIMUTATION = 47;
  /** RegularExpression Id. */
  int ETIMUTATIONTEXT = 48;
  /** RegularExpression Id. */
  int CARACTER6 = 49;
  /** RegularExpression Id. */
  int CARACTER7 = 50;
  /** RegularExpression Id. */
  int ETINUMBERPROMPT = 51;
  /** RegularExpression Id. */
  int ETIFINVALUEPROMPT = 52;
  /** RegularExpression Id. */
  int CARACTER10 = 53;
  /** RegularExpression Id. */
  int NOMFUN = 54;
  /** RegularExpression Id. */
  int ARGUMENTOS = 55;
  /** RegularExpression Id. */
  int NOMBRE = 56;
  /** RegularExpression Id. */
  int ARGUM = 57;
  /** RegularExpression Id. */
  int DESCRIPCI = 58;
  /** RegularExpression Id. */
  int DESCRIPC = 59;
  /** RegularExpression Id. */
  int DESCRIPCION = 60;
  /** RegularExpression Id. */
  int STATEM = 61;
  /** RegularExpression Id. */
  int NOMBREFUN = 62;
  /** RegularExpression Id. */
  int FUNC = 63;
  /** RegularExpression Id. */
  int FINLLAMAFUNCION = 64;
  /** RegularExpression Id. */
  int ARGUMENTO = 65;
  /** RegularExpression Id. */
  int LLFVAR = 66;
  /** RegularExpression Id. */
  int LLFTEXT = 67;
  /** RegularExpression Id. */
  int LLFARG = 68;
  /** RegularExpression Id. */
  int ETIFINLLAMAFUNCION = 69;
  /** RegularExpression Id. */
  int OPADD = 70;
  /** RegularExpression Id. */
  int OPMINUS = 71;
  /** RegularExpression Id. */
  int OPMULTIPLY = 72;
  /** RegularExpression Id. */
  int OPDIVIDE = 73;
  /** RegularExpression Id. */
  int OPEQ = 74;
  /** RegularExpression Id. */
  int OPNEQ = 75;
  /** RegularExpression Id. */
  int OPLT = 76;
  /** RegularExpression Id. */
  int OPLTE = 77;
  /** RegularExpression Id. */
  int OPGT = 78;
  /** RegularExpression Id. */
  int OPGTE = 79;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int XML = 1;
  /** Lexical state. */
  int BLOQUE = 2;
  /** Lexical state. */
  int FINBLOQUE = 3;
  /** Lexical state. */
  int PRINT = 4;
  /** Lexical state. */
  int TEXT1 = 5;
  /** Lexical state. */
  int TEXT = 6;
  /** Lexical state. */
  int SIGUIENTE = 7;
  /** Lexical state. */
  int NOM = 8;
  /** Lexical state. */
  int NOMVAR = 9;
  /** Lexical state. */
  int FINNOMVAR = 10;
  /** Lexical state. */
  int NUM = 11;
  /** Lexical state. */
  int NUM2 = 12;
  /** Lexical state. */
  int SIG = 13;
  /** Lexical state. */
  int TEXTPROMPT = 14;
  /** Lexical state. */
  int FRASEPROMPT = 15;
  /** Lexical state. */
  int FRASEPROMPT2 = 16;
  /** Lexical state. */
  int FRASEPROMPT3 = 17;
  /** Lexical state. */
  int TEXTOPROMPT = 18;
  /** Lexical state. */
  int FUNCION = 19;
  /** Lexical state. */
  int NOMFUNCION = 20;
  /** Lexical state. */
  int ARGUN = 21;
  /** Lexical state. */
  int DESCRIPCIONFUNCION = 22;
  /** Lexical state. */
  int DES = 23;
  /** Lexical state. */
  int DESCRIP = 24;
  /** Lexical state. */
  int STATEMENT = 25;
  /** Lexical state. */
  int LLAMAFUNCION = 26;
  /** Lexical state. */
  int LLAMAFUN = 27;
  /** Lexical state. */
  int ARGUMENTOSFUN = 28;
  /** Lexical state. */
  int ARGU = 29;
  /** Lexical state. */
  int NOMVARLLF = 30;
  /** Lexical state. */
  int FINLLF = 31;
  /** Lexical state. */
  int OP = 32;
  /** Lexical state. */
  int OPLOGIC = 33;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Name>",
    "<NameChar>",
    "<NameStarChar>",
    "<S>",
    "<Entero>",
    "<Flotante>",
    "\"<xml\"",
    "\"<block type=\\\"procedures_defnoreturn\"",
    "\"<block\"",
    "\"<next\"",
    "\"</next\"",
    "\"/xml>\"",
    "<ETIFINBLOQUE>",
    "<ETIPRINT>",
    "<ETIVARSET>",
    "<ETIPROMPT>",
    "<ETINEXT>",
    "<ETIVARGET>",
    "<ETIFINSTATEMENT>",
    "<ETILLAMAFUNCION>",
    "<ETIARGUMENTOS>",
    "<ETIMATHARITHMETIC>",
    "<ETIMATHNUMBER>",
    "<ETIVALUENAMEB>",
    "<ETIIF>",
    "<ETILOGIC>",
    "<ETIDO0>",
    "<FINBLO>",
    "<TEXTOPRINT>",
    "<TEXT2>",
    "<CARACTER>",
    "<ETITEXT>",
    "<ETIPRINTNUM>",
    "<ETIBLOCKGET>",
    "<ETIFINVALU>",
    "<ETIMATHARITHMETIC2>",
    "<CARACTER2>",
    "<CARACTER3>",
    "<ETINAMEVALUE>",
    "<ETIFINVALU2>",
    "<CARACTER8>",
    "<CARACTER9>",
    "<MATHNUMBER>",
    "<FINVALUE>",
    "<VARGET>",
    "<ETIMATHARITHMETIC3>",
    "<ETIMUTATION>",
    "<ETIMUTATIONTEXT>",
    "<CARACTER6>",
    "<CARACTER7>",
    "<ETINUMBERPROMPT>",
    "<ETIFINVALUEPROMPT>",
    "<CARACTER10>",
    "<NOMFUN>",
    "<ARGUMENTOS>",
    "<NOMBRE>",
    "<ARGUM>",
    "<DESCRIPCI>",
    "<DESCRIPC>",
    "<DESCRIPCION>",
    "<STATEM>",
    "<NOMBREFUN>",
    "<FUNC>",
    "<FINLLAMAFUNCION>",
    "<ARGUMENTO>",
    "<LLFVAR>",
    "<LLFTEXT>",
    "<LLFARG>",
    "<ETIFINLLAMAFUNCION>",
    "\"field name=\\\"OP\\\">ADD\"",
    "\"field name=\\\"OP\\\">MINUS\"",
    "\"field name=\\\"OP\\\">MULTIPLY\"",
    "\"field name=\\\"OP\\\">DIVIDE\"",
    "\"field name=\\\"OP\\\">EQ\"",
    "\"field name=\\\"OP\\\">NEQ\"",
    "\"field name=\\\"OP\\\">LT\"",
    "\"field name=\\\"OP\\\">LTE\"",
    "\"field name=\\\"OP\\\">GT\"",
    "\"field name=\\\"OP\\\">GTE\"",
    "<token of kind 80>",
  };

}
